name: Deploy to Koyeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#       install
      - name: Install Koyeb CLI
        uses: koyeb/action-install-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

#        deploy
      - name: Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: eshop-adpro-fideligo
          service-name: eshop-service
          git-builder: buildpack
          service-env: SERVER_PORT=8080
          service-ports: 8080:http
          service-routes: /:8080
          skip-cache: true